export const CREATE_EXPENSE_ERROR = 'CREATE_EXPENSE_ERROR';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';

export const DELETE_EXPENSE_ERROR = 'DELETE_EXPENSE_ERROR';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';

export const UPDATE_EXPENSE_ERROR = 'UPDATE_EXPENSE_ERROR';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';


export const CREATE_INCOME_ERROR = 'CREATE_INCOME_ERROR';
export const CREATE_INCOME_SUCCESS = 'CREATE_INCOME_SUCCESS';

export const DELETE_INCOME_ERROR = 'DELETE_INCOME_ERROR';
export const DELETE_INCOME_SUCCESS = 'DELETE_INCOME_SUCCESS';

export const UPDATE_INCOME_ERROR = 'UPDATE_INCOME_ERROR';
export const UPDATE_INCOME_SUCCESS = 'UPDATE_INCOME_SUCCESS';
